apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-deployment
  labels:
    app: console-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: console-deployment
    spec:
      containers:
      - name: dotent-docker-k8s
        image: localhost:5000/dotnet-docker-k8s
        imagePullPolicy: IfNotPresent
        env:
        - name: ARG1
          value: ".NET"
        - name: ARG2
          value: "Docker + K8s"
  selector:
    matchLabels:
      app: console-deployment